import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import  Link  from "next/link";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  aaa,
  bbb
}: Readonly<{
  children: React.ReactNode;
  aaa:React.ReactNode;
  bbb:React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
      >
        <div style={{color:'red'}}>
          <Link href='/'>home</Link>
          <br/>
          <Link href='/visitors'>visitors</Link>
        </div>
        {children}
        <div>
        {aaa}
        {bbb}
        </div>
        
      </body>
    </html>
  );
}
